POKEMON_DATABASE = [
    {"name": "Venusaur", "t1": 4, "t2": 7}, {"name": "Charizard", "t1": 1, "t2": 9},
    {"name": "Blastoise", "t1": 2, "t2": None}, {"name": "Beedrill", "t1": 11, "t2": 7},
    {"name": "Pidgeot", "t1": 0, "t2": 9}, {"name": "Arbok", "t1": 7, "t2": None},
    {"name": "Pikachu", "t1": 3, "t2": None}, {"name": "Raichu", "t1": 3, "t2": None},
    {"name": "Raichu (Alola)", "t1": 3, "t2": 10}, {"name": "Clefable", "t1": 17, "t2": None},
    {"name": "Ninetales", "t1": 1, "t2": None}, {"name": "Ninetales (Alola)", "t1": 5, "t2": 17},
    {"name": "Vileplume", "t1": 4, "t2": 7}, {"name": "Arcanine", "t1": 1, "t2": None},
    {"name": "Arcanine (Hisui)", "t1": 1, "t2": 12}, {"name": "Alakazam", "t1": 10, "t2": None},
    {"name": "Machamp", "t1": 6, "t2": None}, {"name": "Victreebel", "t1": 4, "t2": 7},
    {"name": "Slowbro", "t1": 2, "t2": 10}, {"name": "Slowbro (Galar)", "t1": 7, "t2": 10},
    {"name": "Gengar", "t1": 13, "t2": 7}, {"name": "Kangaskhan", "t1": 0, "t2": None},
    {"name": "Starmie", "t1": 2, "t2": 10}, {"name": "Pinsir", "t1": 11, "t2": None},
    {"name": "Tauros", "t1": 0, "t2": None}, {"name": "Tauros (Paldea - Combat)", "t1": 6, "t2": None},
    {"name": "Tauros (Paldea - Blaze)", "t1": 6, "t2": 1}, {"name": "Tauros (Paldea - Aqua)", "t1": 6, "t2": 2},
    {"name": "Gyarados", "t1": 2, "t2": 9}, {"name": "Ditto", "t1": 0, "t2": None},
    {"name": "Vaporeon", "t1": 2, "t2": None}, {"name": "Jolteon", "t1": 3, "t2": None},
    {"name": "Flareon", "t1": 1, "t2": None}, {"name": "Aerodactyl", "t1": 12, "t2": 9},
    {"name": "Snorlax", "t1": 0, "t2": None}, {"name": "Dragonite", "t1": 14, "t2": 9},
    {"name": "Meganium", "t1": 4, "t2": None}, {"name": "Typhlosion", "t1": 1, "t2": None},
    {"name": "Typhlosion (Hisui)", "t1": 1, "t2": 13}, {"name": "Feraligatr", "t1": 2, "t2": None},
    {"name": "Ariados", "t1": 11, "t2": 7}, {"name": "Ampharos", "t1": 3, "t2": None},
    {"name": "Azumarill", "t1": 2, "t2": 17}, {"name": "Politoed", "t1": 2, "t2": None},
    {"name": "Espeon", "t1": 10, "t2": None}, {"name": "Umbreon", "t1": 15, "t2": None},
    {"name": "Slowking", "t1": 2, "t2": 10}, {"name": "Slowking (Galar)", "t1": 7, "t2": 10},
    {"name": "Forretress", "t1": 11, "t2": 16}, {"name": "Steelix", "t1": 16, "t2": 8},
    {"name": "Qwilfish", "t1": 2, "t2": 7}, {"name": "Scizor", "t1": 11, "t2": 16},
    {"name": "Heracross", "t1": 11, "t2": 6}, {"name": "Skarmory", "t1": 16, "t2": 9},
    {"name": "Houndoom", "t1": 15, "t2": 1}, {"name": "Tyranitar", "t1": 12, "t2": 15},
    {"name": "Sceptile", "t1": 4, "t2": None}, {"name": "Blaziken", "t1": 1, "t2": 6},
    {"name": "Swampert", "t1": 2, "t2": 8}, {"name": "Pelipper", "t1": 2, "t2": 9},
    {"name": "Gardevoir", "t1": 10, "t2": 17}, {"name": "Sableye", "t1": 15, "t2": 13},
    {"name": "Mawile", "t1": 16, "t2": 17}, {"name": "Aggron", "t1": 16, "t2": 12},
    {"name": "Medicham", "t1": 6, "t2": 10}, {"name": "Manectric", "t1": 3, "t2": None},
    {"name": "Sharpedo", "t1": 2, "t2": 15}, {"name": "Camerupt", "t1": 1, "t2": 8},
    {"name": "Torkoal", "t1": 1, "t2": None}, {"name": "Altaria", "t1": 14, "t2": 9},
    {"name": "Milotic", "t1": 2, "t2": None}, {"name": "Castform", "t1": 0, "t2": None},
    {"name": "Banette", "t1": 13, "t2": None}, {"name": "Chimecho", "t1": 10, "t2": None},
    {"name": "Absol", "t1": 15, "t2": None}, {"name": "Glalie", "t1": 5, "t2": None},
    {"name": "Metagross", "t1": 16, "t2": 10}, {"name": "Torterra", "t1": 4, "t2": 8},
    {"name": "Infernape", "t1": 1, "t2": 6}, {"name": "Empoleon", "t1": 2, "t2": 16},
    {"name": "Staraptor", "t1": 0, "t2": 9}, {"name": "Luxray", "t1": 3, "t2": None},
    {"name": "Roserade", "t1": 4, "t2": 7}, {"name": "Rampardos", "t1": 12, "t2": None},
    {"name": "Bastiodon", "t1": 12, "t2": 16}, {"name": "Lopunny", "t1": 0, "t2": None},
    {"name": "Spiritomb", "t1": 13, "t2": 15}, {"name": "Garchomp", "t1": 14, "t2": 8},
    {"name": "Lucario", "t1": 6, "t2": 16}, {"name": "Hippowdon", "t1": 8, "t2": None},
    {"name": "Toxicroak", "t1": 7, "t2": 6}, {"name": "Abomasnow", "t1": 4, "t2": 5},
    {"name": "Weavile", "t1": 15, "t2": 5}, {"name": "Rhyperior", "t1": 8, "t2": 12},
    {"name": "Leafeon", "t1": 4, "t2": None}, {"name": "Glaceon", "t1": 5, "t2": None},
    {"name": "Gliscor", "t1": 8, "t2": 9}, {"name": "Mamoswine", "t1": 5, "t2": 8},
    {"name": "Gallade", "t1": 10, "t2": 6}, {"name": "Froslass", "t1": 5, "t2": 13},
    {"name": "Rotom", "t1": 3, "t2": 13}, {"name": "Serperior", "t1": 4, "t2": None},
    {"name": "Emboar", "t1": 1, "t2": 6}, {"name": "Samurott", "t1": 2, "t2": None},
    {"name": "Samurott (Hisui)", "t1": 2, "t2": 15}, {"name": "Watchog", "t1": 0, "t2": None},
    {"name": "Liepard", "t1": 15, "t2": None}, {"name": "Simisage", "t1": 4, "t2": None},
    {"name": "Simisear", "t1": 1, "t2": None}, {"name": "Simipour", "t1": 2, "t2": None},
    {"name": "Musharna", "t1": 10, "t2": None}, {"name": "Excadrill", "t1": 8, "t2": 16},
    {"name": "Audino", "t1": 0, "t2": None}, {"name": "Conkeldurr", "t1": 6, "t2": None},
    {"name": "Scolipede", "t1": 11, "t2": 7}, {"name": "Whimsicott", "t1": 4, "t2": 17},
    {"name": "Krookodile", "t1": 8, "t2": 15}, {"name": "Scrafty", "t1": 15, "t2": 6},
    {"name": "Cofagrigus", "t1": 13, "t2": None}, {"name": "Garbodor", "t1": 7, "t2": None},
    {"name": "Zoroark", "t1": 15, "t2": None}, {"name": "Zoroark (Hisui)", "t1": 0, "t2": 13},
    {"name": "Reuniclus", "t1": 10, "t2": None}, {"name": "Vanilluxe", "t1": 5, "t2": None},
    {"name": "Emolga", "t1": 3, "t2": 9}, {"name": "Eelektross", "t1": 3, "t2": None},
    {"name": "Chandelure", "t1": 13, "t2": 1}, {"name": "Beartice", "t1": 5, "t2": None},
    {"name": "Stunfisk", "t1": 8, "t2": 3}, {"name": "Stunfisk (Galar)", "t1": 8, "t2": 16},
    {"name": "Golurk", "t1": 8, "t2": 13}, {"name": "Hydreigon", "t1": 15, "t2": 14},
    {"name": "Volcarona", "t1": 11, "t2": 1}, {"name": "Chesnaught", "t1": 4, "t2": 6},
    {"name": "Delphox", "t1": 1, "t2": 10}, {"name": "Greninja", "t1": 2, "t2": 15},
    {"name": "Diggersby", "t1": 0, "t2": 8}, {"name": "Talonflame", "t1": 1, "t2": 9},
    {"name": "Vivillon", "t1": 11, "t2": 9}, {"name": "Pyroar (M)", "t1": 1, "t2": 0},
    {"name": "Pyroar (F)", "t1": 1, "t2": 0}, {"name": "Floette (Eternal)", "t1": 17, "t2": None},
    {"name": "Florges", "t1": 17, "t2": None}, {"name": "Pangoro", "t1": 6, "t2": 15},
    {"name": "Furfrou", "t1": 0, "t2": None}, {"name": "Meowstic (M)", "t1": 10, "t2": None},
    {"name": "Meowstic (F)", "t1": 10, "t2": None}, {"name": "Aegislash", "t1": 16, "t2": 13},
    {"name": "Aromatisse", "t1": 17, "t2": None}, {"name": "Slurpuff", "t1": 17, "t2": None},
    {"name": "Malamar", "t1": 15, "t2": 10}, {"name": "Barbaracle", "t1": 12, "t2": 2},
    {"name": "Dragalge", "t1": 7, "t2": 14}, {"name": "Clawitzer", "t1": 2, "t2": None},
    {"name": "Heliolisk", "t1": 3, "t2": 0}, {"name": "Tyrantrum", "t1": 12, "t2": 14},
    {"name": "Aurorus", "t1": 12, "t2": 5}, {"name": "Sylveon", "t1": 17, "t2": None},
    {"name": "Hawlucha", "t1": 6, "t2": 9}, {"name": "Dedenne", "t1": 3, "t2": 17},
    {"name": "Goodra", "t1": 14, "t2": None}, {"name": "Goodra (Hisui)", "t1": 16, "t2": 14},
    {"name": "Klefki", "t1": 16, "t2": 17}, {"name": "Trevenant", "t1": 13, "t2": 4},
    {"name": "Gourgeist", "t1": 13, "t2": 4}, {"name": "Avalugg", "t1": 5, "t2": None},
    {"name": "Avalugg (Hisui)", "t1": 5, "t2": 12}, {"name": "Noivern", "t1": 9, "t2": 14},
    {"name": "Decidueye", "t1": 4, "t2": 13}, {"name": "Decidueye (Hisui)", "t1": 4, "t2": 6},
    {"name": "Incineroar", "t1": 1, "t2": 15}, {"name": "Primarina", "t1": 2, "t2": 17},
    {"name": "Toucannon", "t1": 0, "t2": 9}, {"name": "Crabominable", "t1": 6, "t2": 5},
    {"name": "Lycanroc", "t1": 12, "t2": None}, {"name": "Toxapex", "t1": 7, "t2": 2},
    {"name": "Mudsdale", "t1": 8, "t2": None}, {"name": "Araquanid", "t1": 2, "t2": 11},
    {"name": "Salazzle", "t1": 7, "t2": 1}, {"name": "Tsareena", "t1": 4, "t2": None},
    {"name": "Oranguru", "t1": 0, "t2": 10}, {"name": "Passimian", "t1": 6, "t2": None},
    {"name": "Mimikyu", "t1": 13, "t2": 17}, {"name": "Drampa", "t1": 0, "t2": 14},
    {"name": "Kommo-o", "t1": 14, "t2": 6}, {"name": "Corviknight", "t1": 9, "t2": 16},
    {"name": "Flapple", "t1": 4, "t2": 14}, {"name": "Appletun", "t1": 4, "t2": 14},
    {"name": "Sandaconda", "t1": 8, "t2": None}, {"name": "Polteageist", "t1": 13, "t2": None},
    {"name": "Hatterene", "t1": 10, "t2": 17}, {"name": "Grimmsnarl", "t1": 15, "t2": 17},
    {"name": "Mr. Rime", "t1": 5, "t2": 10}, {"name": "Runerigus", "t1": 8, "t2": 13},
    {"name": "Alcremie", "t1": 17, "t2": None}, {"name": "Falinks", "t1": 6, "t2": None},
    {"name": "Morpeko", "t1": 3, "t2": 15}, {"name": "Dragapult", "t1": 14, "t2": 13},
    {"name": "Wyrdeer", "t1": 0, "t2": 10}, {"name": "Kleavor", "t1": 11, "t2": 12},
    {"name": "Basculegion (M)", "t1": 2, "t2": 13}, {"name": "Basculegion (F)", "t1": 2, "t2": 13},
    {"name": "Sneasler", "t1": 6, "t2": 7}, {"name": "Overqwil", "t1": 15, "t2": 7},
    {"name": "Meowscarada", "t1": 4, "t2": 15}, {"name": "Skeledirge", "t1": 1, "t2": 13},
    {"name": "Quaquaval", "t1": 2, "t2": 6}, {"name": "Maushold", "t1": 0, "t2": None},
    {"name": "Garganacl", "t1": 12, "t2": None}, {"name": "Armarouge", "t1": 1, "t2": 10},
    {"name": "Ceruledge", "t1": 1, "t2": 13}, {"name": "Bellibolt", "t1": 3, "t2": None},
    {"name": "Scovillain", "t1": 4, "t2": 1}, {"name": "Espathra", "t1": 10, "t2": None},
    {"name": "Tinkaton", "t1": 17, "t2": 16}, {"name": "Palafin", "t1": 2, "t2": None},
    {"name": "Orthworm", "t1": 16, "t2": None}, {"name": "Glimmora", "t1": 12, "t2": 7},
    {"name": "Houndstone", "t1": 13, "t2": None}, {"name": "Annihilape", "t1": 6, "t2": 13},
    {"name": "Farigiraf", "t1": 0, "t2": 10}, {"name": "Kingambit", "t1": 15, "t2": 16},
    {"name": "Gholdengo", "t1": 16, "t2": 13}, {"name": "Sinistcha", "t1": 4, "t2": 13},
    {"name": "Archaludon", "t1": 16, "t2": 14}, {"name": "Hydrapple", "t1": 4, "t2": 14}
]